# Generated by Django 5.1.5 on 2025-01-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aloraapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='payment_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
