# Generated by Django 5.1.1 on 2025-03-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aloraapp', '0002_alter_bookings_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='event_status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.FileField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Events',
        ),
    ]
