# Generated by Django 5.1.1 on 2025-03-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aloraapp', '0003_alter_bookings_event_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='decoration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aloraapp.decoration'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aloraapp.food'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='photography_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
