# Generated by Django 5.1.1 on 2025-04-09 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aloraapp', '0004_alter_bookings_decoration_alter_bookings_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='decoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aloraapp.decoration'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aloraapp.food'),
        ),
    ]
