# Generated by Django 5.1.1 on 2025-04-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aloraapp', '0005_alter_bookings_decoration_alter_bookings_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='no_of_people',
            new_name='no_of_persons',
        ),
    ]
